apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: ci-serverless-operator
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-operators
  packages: serverless-operator
  source: redhat-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
spec:
  channel: techpreview
  name: serverless-operator
  source: ci-serverless-operator
  sourceNamespace: openshift-operators
